QT *= network xml sql
CONFIG *= c++14

SOURCES *= \
    $$PWD/src/abstractdropboxjob.cpp \
    $$PWD/src/abstractdropboxjobprivate.cpp \
    $$PWD/src/abstractjob.cpp \
    $$PWD/src/abstractjobfactory.cpp \
    $$PWD/src/abstractjobfactoryprivate.cpp \
    $$PWD/src/abstractjobprivate.cpp \
    $$PWD/src/abstractwebdavjob.cpp \
    $$PWD/src/abstractwebdavjobprivate.cpp \
    $$PWD/src/compositejob.cpp \
    $$PWD/src/compositejobprivate.cpp \
    $$PWD/src/createdirectoryjob.cpp \
    $$PWD/src/createdirectoryjobprivate.cpp \
    $$PWD/src/deletejob.cpp \
    $$PWD/src/deletejobprivate.cpp \
    $$PWD/src/directorysynchronizer.cpp \
    $$PWD/src/directorysynchronizerprivate.cpp \
    $$PWD/src/downloadfilejob.cpp \
    $$PWD/src/downloadfilejobprivate.cpp \
    $$PWD/src/dropboxcreatedirectoryjob.cpp \
    $$PWD/src/dropboxcreatedirectoryjobprivate.cpp \
    $$PWD/src/dropboxdeletejob.cpp \
    $$PWD/src/dropboxdeletejobprivate.cpp \
    $$PWD/src/dropboxdownloadfilejob.cpp \
    $$PWD/src/dropboxdownloadfilejobprivate.cpp \
    $$PWD/src/dropboxgetfileinfojob.cpp \
    $$PWD/src/dropboxgetfileinfojobprivate.cpp \
    $$PWD/src/dropboxjobfactory.cpp \
    $$PWD/src/dropboxjobfactoryprivate.cpp \
    $$PWD/src/dropboxlistfilesjob.cpp \
    $$PWD/src/dropboxlistfilesjobprivate.cpp \
    $$PWD/src/dropboxuploadfilejob.cpp \
    $$PWD/src/dropboxuploadfilejobprivate.cpp \
    $$PWD/src/fileinfo.cpp \
    $$PWD/src/fileinfoprivate.cpp \
    $$PWD/src/getfileinfojob.cpp \
    $$PWD/src/getfileinfojobprivate.cpp \
    $$PWD/src/jsonsyncstatedatabase.cpp \
    $$PWD/src/jsonsyncstatedatabaseprivate.cpp \
    $$PWD/src/libsynqclient.cpp \
    $$PWD/src/listfilesjob.cpp \
    $$PWD/src/listfilesjobprivate.cpp \
    $$PWD/src/nextcloudloginflow.cpp \
    $$PWD/src/nextcloudloginflowprivate.cpp \
    $$PWD/src/sqlsyncstatedatabase.cpp \
    $$PWD/src/sqlsyncstatedatabaseprivate.cpp \
    $$PWD/src/syncstatedatabase.cpp \
    $$PWD/src/syncstatedatabaseprivate.cpp \
    $$PWD/src/syncstateentry.cpp \
    $$PWD/src/syncstateentryprivate.cpp \
    $$PWD/src/uploadfilejob.cpp \
    $$PWD/src/uploadfilejobprivate.cpp \
    $$PWD/src/webdavcreatedirectoryjob.cpp \
    $$PWD/src/webdavcreatedirectoryjobprivate.cpp \
    $$PWD/src/webdavdeletejob.cpp \
    $$PWD/src/webdavdeletejobprivate.cpp \
    $$PWD/src/webdavdownloadfilejob.cpp \
    $$PWD/src/webdavdownloadfilejobprivate.cpp \
    $$PWD/src/webdavgetfileinfojob.cpp \
    $$PWD/src/webdavgetfileinfojobprivate.cpp \
    $$PWD/src/webdavjobfactory.cpp \
    $$PWD/src/webdavjobfactoryprivate.cpp \
    $$PWD/src/webdavlistfilesjob.cpp \
    $$PWD/src/webdavlistfilesjobprivate.cpp \
    $$PWD/src/webdavuploadfilejob.cpp \
    $$PWD/src/webdavuploadfilejobprivate.cpp

HEADERS *= \
    $$PWD/inc/SynqClient/AbstractDropboxJob \
    $$PWD/inc/SynqClient/AbstractJob \
    $$PWD/inc/SynqClient/AbstractJobFactory \
    $$PWD/inc/SynqClient/AbstractWebDAVJob \
    $$PWD/inc/SynqClient/CompositeJob \
    $$PWD/inc/SynqClient/CreateDirectoryJob \
    $$PWD/inc/SynqClient/DeleteJob \
    $$PWD/inc/SynqClient/DirectorySynchronizer \
    $$PWD/inc/SynqClient/DownloadFileJob \
    $$PWD/inc/SynqClient/DropboxCreateDirectoryJob \
    $$PWD/inc/SynqClient/DropboxDeleteJob \
    $$PWD/inc/SynqClient/DropboxDownloadFileJob \
    $$PWD/inc/SynqClient/DropboxGetFileInfoJob \
    $$PWD/inc/SynqClient/DropboxJobFactory \
    $$PWD/inc/SynqClient/DropboxListFilesJob \
    $$PWD/inc/SynqClient/DropboxUploadFileJob \
    $$PWD/inc/SynqClient/FileInfo \
    $$PWD/inc/SynqClient/GetFileInfoJob \
    $$PWD/inc/SynqClient/JSONSyncStateDatabase \
    $$PWD/inc/SynqClient/ListFilesJob \
    $$PWD/inc/SynqClient/NextCloudLoginFlow \
    $$PWD/inc/SynqClient/SQLSyncStateDatabase \
    $$PWD/inc/SynqClient/SyncStateDatabase \
    $$PWD/inc/SynqClient/SyncStateEntry \
    $$PWD/inc/SynqClient/UploadFileJob \
    $$PWD/inc/SynqClient/WebDAVCreateDirectoryJob \
    $$PWD/inc/SynqClient/WebDAVDeleteJob \
    $$PWD/inc/SynqClient/WebDAVDownloadFileJob \
    $$PWD/inc/SynqClient/WebDAVGetFileInfoJob \
    $$PWD/inc/SynqClient/WebDAVJobFactory \
    $$PWD/inc/SynqClient/WebDAVListFilesJob \
    $$PWD/inc/SynqClient/WebDAVUploadFileJob \
    $$PWD/inc/SynqClient/abstractdropboxjob.h \
    $$PWD/inc/SynqClient/abstractjob.h \
    $$PWD/inc/SynqClient/abstractjobfactory.h \
    $$PWD/inc/SynqClient/abstractwebdavjob.h \
    $$PWD/inc/SynqClient/compositejob.h \
    $$PWD/inc/SynqClient/createdirectoryjob.h \
    $$PWD/inc/SynqClient/deletejob.h \
    $$PWD/inc/SynqClient/directorysynchronizer.h \
    $$PWD/inc/SynqClient/downloadfilejob.h \
    $$PWD/inc/SynqClient/dropboxcreatedirectoryjob.h \
    $$PWD/inc/SynqClient/dropboxdeletejob.h \
    $$PWD/inc/SynqClient/dropboxdownloadfilejob.h \
    $$PWD/inc/SynqClient/dropboxgetfileinfojob.h \
    $$PWD/inc/SynqClient/dropboxjobfactory.h \
    $$PWD/inc/SynqClient/dropboxlistfilesjob.h \
    $$PWD/inc/SynqClient/dropboxuploadfilejob.h \
    $$PWD/inc/SynqClient/fileinfo.h \
    $$PWD/inc/SynqClient/getfileinfojob.h \
    $$PWD/inc/SynqClient/jsonsyncstatedatabase.h \
    $$PWD/inc/SynqClient/libsynqclient_global.h \
    $$PWD/inc/SynqClient/libsynqclient.h \
    $$PWD/inc/SynqClient/listfilesjob.h \
    $$PWD/inc/SynqClient/nextcloudloginflow.h \
    $$PWD/inc/SynqClient/sqlsyncstatedatabase.h \
    $$PWD/inc/SynqClient/syncstatedatabase.h \
    $$PWD/inc/SynqClient/syncstateentry.h \
    $$PWD/inc/SynqClient/uploadfilejob.h \
    $$PWD/inc/SynqClient/webdavcreatedirectoryjob.h \
    $$PWD/inc/SynqClient/webdavdeletejob.h \
    $$PWD/inc/SynqClient/webdavdownloadfilejob.h \
    $$PWD/inc/SynqClient/webdavgetfileinfojob.h \
    $$PWD/inc/SynqClient/webdavjobfactory.h \
    $$PWD/inc/SynqClient/webdavlistfilesjob.h \
    $$PWD/inc/SynqClient/webdavuploadfilejob.h \
    $$PWD/src/abstractdropboxjobprivate.h \
    $$PWD/src/abstractjobfactoryprivate.h \
    $$PWD/src/abstractjobprivate.h \
    $$PWD/src/abstractwebdavjobprivate.h \
    $$PWD/inc/SynqClient/SynqClient \
    $$PWD/src/changetree.h \
    $$PWD/src/compositejobprivate.h \
    $$PWD/src/createdirectoryjobprivate.h \
    $$PWD/src/deletejobprivate.h \
    $$PWD/src/directorysynchronizerprivate.h \
    $$PWD/src/downloadfilejobprivate.h \
    $$PWD/src/dropboxcreatedirectoryjobprivate.h \
    $$PWD/src/dropboxdeletejobprivate.h \
    $$PWD/src/dropboxdownloadfilejobprivate.h \
    $$PWD/src/dropboxgetfileinfojobprivate.h \
    $$PWD/src/dropboxjobfactoryprivate.h \
    $$PWD/src/dropboxlistfilesjobprivate.h \
    $$PWD/src/dropboxuploadfilejobprivate.h \
    $$PWD/src/fileinfoprivate.h \
    $$PWD/src/getfileinfojobprivate.h \
    $$PWD/src/jsonsyncstatedatabaseprivate.h \
    $$PWD/src/listfilesjobprivate.h \
    $$PWD/src/nextcloudloginflowprivate.h \
    $$PWD/src/sqlsyncstatedatabaseprivate.h \
    $$PWD/src/syncactions.h \
    $$PWD/src/syncstatedatabaseprivate.h \
    $$PWD/src/syncstateentryprivate.h \
    $$PWD/src/uploadfilejobprivate.h \
    $$PWD/src/webdavcreatedirectoryjobprivate.h \
    $$PWD/src/webdavdeletejobprivate.h \
    $$PWD/src/webdavdownloadfilejobprivate.h \
    $$PWD/src/webdavgetfileinfojobprivate.h \
    $$PWD/src/webdavjobfactoryprivate.h \
    $$PWD/src/webdavlistfilesjobprivate.h \
    $$PWD/src/webdavuploadfilejobprivate.h

INCLUDEPATH *= $$PWD/inc
