FROM fedora

RUN \
    dnf install -y \
        cmake \
        cppcheck \
        doxygen \
        gcc \
        gcc-c++ \
        make \
        ninja-build \
        python3-pip \
        qt5-qtbase-devel \
        && \
    pip install \
        sphinx \
        sphinx_rtd_theme \
        breathe
